# variables that can be put on the x and y axes
axis_vars <- c(
  "Date - game date" = "Date",
  "Age - age at start of season" = "Age",
  "Pos - position" = "Pos",
  "GS - games started" = "GS",
  "MP - minutes played" = "MP",
  "FG - field goals" = "FG",
  "FGA - field goal attempts" = "FGA",
  "FG% - field goal percentage" = "FG.",
  "2P - 2-point field goals" = "X2P",
  "2PA - 2-point field goal attempts" = "X2PA",
  "2P% - 2-point field goal percentage" = "X2P.",
  "3P - 3-point field goals" = "X3P",
  "3PA - 3-point field goal attempts" = "X3PA",
  "3P% - 3-point field goal percentage" = "X3P.",
  "FT - free throws" = "FT",
  "FTA - free throw attempts" = "FTA",
  "FT% - free throw percentage" = "FT.",
  "ORB - offensive rebounds" = "ORB",
  "DRB - defensive rebounds" = "DRB",
  "TRB - total rebounds" = "TRB",
  "AST - assists" = "AST",
  "STL - steals" = "STL",
  "BLK - blocks" = "BLK",
  "TOV - turnovers" = "TOV",
  "PF - personal fouls" = "PF",
  "PTS - points" = "PTS",
  "GmSc - game score" = "GmSc"
)