---
title: "EM Clustering Analysis"
author: "Isys"
date: "6/5/2018"
output: html_document
---

library(factoextra)
library(gmodels)
library(descr)
library(dplyr)
library(tidyr)
library(mclust)
library(cluster)
library(FactoMineR)
library(Matching)

setwd("/Users/isysjo/Documents/Summer REU 2018/SportsAnalytics/R")

source('preprocess_individuals.R')



# new data
clean_individual_player_data <- function(player_table) {
  player_table <- player_table %>%
    filter(MIN > 0)
  return(player_table)
}

# modifications to load all players
path_to_files <- '../Data/2017_2018/'
filelist = paste0(path_to_files, list.files(path_to_files, 'all_per_minute_2017_2018.csv'))
all_players <- read.csv(filelist)
# get the training set and do same things to training set as full set
ap_training <- read.csv('../Data/train_test/player_train.csv')

clean_load <- all_players %>% clean_individual_player_data()

# get aggregate player data
 aggregate_players <- clean_load
aggregate_training <- ap_training %>% clean_individual_player_data()

# remove players who haven't played more than 50 minutes
aggregate_players <- aggregate_players %>% filter(MIN > 50)
aggregate_training <- aggregate_training %>% filter(MIN > 50)

# get numeric data (excluding result, GS, MP, and GmSc)
numeric <- aggregate_players %>% select(FGM:BOX_OUTS, -POS)
numeric_training <- aggregate_training %>% select(FGM:BOX_OUTS, -POS)

# set NA percentages to 0
numeric[is.na(numeric)] <- 0
numeric_training[is.na(numeric_training)] <- 0

## scale numeric data before clustering
numeric_scaled <- scale(numeric)
ns_training <- scale(numeric_training)

## clustering data not includng PTS & PLUS_MINUS
chosen <- aggregate_players %>% select(FGM:BOX_OUTS, -POS, -PTS, -PLUS_MINUS)
chosen[is.na(chosen)] <- 0
chosen_scaled <- scale(chosen) 

filtered_training <- aggregate_training %>% select(FGM:BOX_OUTS, -POS, -PTS, -PLUS_MINUS)
filtered_training[is.na(filtered_training)] <- 0
filtered_scaled <- scale(filtered_training)

## ks test function to check signifiant attributes of cluster
group_comparison <- function(group_1) {
    pvals <- c()
    for(i in 1:length(filtered_training[1,])){
        if (length(group_1) == length(filtered_training[1,])) {
              test <- ks.boot(group_1[i], filtered_training[,i], alternative = "two.sided")
        }
        else { test <- ks.boot(group_1[,i], filtered_training[,i], alternative = "two.sided") }
        pvals[i] <- test$ks$p.value
    }
    return(pvals)
}

### EM clustering on training set
## model clustering on data
train_clust <- Mclust(filtered_training, G=1:9, modelNames = mclust.options("emModelNames"))
tcom <- clustCombi(train_clust)
classes <- unlist(tcom$classification[4])

pcat <- PCA(ns_training)

clusters_added_t <- cbind(aggregate_training, cluster = classes)
clusters_added_t <- cbind(clusters_added_t, Name = aggregate_training$PLAYER_NAME )
plot(pcat, choix = "ind",col.ind=ifelse(clusters_added_t$cluster ==1, "red", ifelse(clusters_added_t$cluster ==2, "blue", ifelse(clusters_added_t$cluster ==4, "green", "black"))), label = "none")

## make table of attributes and the ks-test p-values for each cluster
cluster_1 <- filtered_scaled[which(clusters_added_t$cluster == 1),]
cluster_2 <- filtered_scaled[which(clusters_added_t$cluster == 2),]
cluster_3 <- filtered_scaled[which(clusters_added_t$cluster == 3),]
cluster_4 <- filtered_scaled[which(clusters_added_t$cluster == 4),]

plist <- list()
plist[[1]] <- group_comparison(cluster_1)
plist[[2]] <- group_comparison(cluster_2)
plist[[3]] <- group_comparison(cluster_3)
plist[[4]] <- group_comparison(cluster_4)

em_val_trix <- do.call(rbind, plist)
colnames(em_val_trix) <- colnames(filtered_training)
rownames(em_val_trix) <- c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4")

## doing PCA and the clustering and color coding based on components
pcat_coord <- pcat$ind$coord
pcat_coord[is.na(pcat_coord)] <- 0
pcat_coord_scaled <- scale(pcat_coord)

model_clust_pca <- Mclust(pcat_coord_scaled, G=1:9, modelNames = mclust.options("emModelNames"))
classes_pca <- clustCombi(model_clust_pca)
#   given the optimal number of clusters given by G in model_clust_pca
#   use the associated classifications as the assignments
clusters_pcat <- unlist(classes_pca$classification[3])
clusters_PCA <- cbind(pcat_coord_scaled, cluster = clusters_pcat) %>% as.data.frame()
clusters_PCA <- cbind(clusters_PCA, Name = aggregate_training$PLAYER_NAME) %>% as.data.frame()

plot(pcat, choix = "ind",col.ind=ifelse(clusters_PCA$cluster ==1, "red", ifelse(clusters_PCA$cluster ==2, "blue", ifelse(clusters_PCA$cluster ==4, "green", "black"))), label = "none")


## make table of attributes and the ks-test p-values for each cluster  
pca_1 <- filtered_scaled[which(clusters_PCA$cluster == 1),]
pca_2 <- filtered_scaled[which(clusters_PCA$cluster == 2),]
pca_3 <- filtered_scaled[which(clusters_PCA$cluster == 3),]

pca_list <- list()
pca_list[[1]] <- group_comparison(pca_1)
pca_list[[2]] <- group_comparison(pca_2)
pca_list[[3]] <- group_comparison(pca_3)

em_pca_trix <- do.call(rbind, pca_list)
colnames(em_pca_trix) <- colnames(filtered_training)
rownames(em_pca_trix) <- c("Cluster 1", "Cluster 2", "Cluster 3")











### EM clustering on full data set
## do model clustering on data
model_clust <- Mclust(numeric_scaled, G=1:9, modelNames = mclust.options("emModelNames"))
combi <- clustCombi(model_clust)
classifications <- unlist(combi$classification[4])


set.seed("123")

clusters_added_EM <- cbind(aggregate_players, cluster = classifications)
clusters_added_EM <- cbind(clusters_added_EM, Name = aggregate_players$PLAYER_NAME )
plot(pca, choix = "ind",col.ind=ifelse(clusters_added_EM$cluster ==1, "red", ifelse(clusters_added_EM$cluster ==2, "blue", ifelse(clusters_added_EM$cluster ==4, "green", "black"))), label = "none")

## doing PCA and the clustering and color coding based on components
pca <- PCA(numeric_scaled)
pca_coord <- pca$ind$coord
pca_coord[is.na(pca_coord)] <- 0
pca_coord_scaled <- scale(pca_coord)

model_clust_pca2 <- Mclust(pca_coord_scaled, G=1:9, modelNames = mclust.options("emModelNames"))
combi_pca <- clustCombi(model_clust_pca2)
#   given the optimal number of clusters given by G in model_clust_pca
#   use the associated classifications as the assignments
clusters_pca <- unlist(combi_pca$classification[3])
clusters_added_PCA <- cbind(pca_coord_scaled, cluster = clusters_pca) %>% as.data.frame()
clusters_added_PCA <- cbind(clusters_added_PCA, Name = aggregate_players$PLAYER_NAME) %>% as.data.frame()

plot(pca, choix = "ind",col.ind=ifelse(clusters_added_PCA$cluster ==1, "red", ifelse(clusters_added_PCA$cluster ==2, "blue", ifelse(clusters_added_PCA$cluster ==4, "green", "black"))), label = "none")


# Pairwise Scatter Plots s
clPairs(pca_coord_scaled, cl = clusters_added_PCA$cluster)
# table of correlations
cor(pca_coord_scaled)