---
title: "Hierclustering Analysis Lineups"
author: "Isys"
date: "June 21, 2018"
output: html_document
---

library(cluster)
library(factoextra)
library(mclust)
library(descr)
library(dplyr)
library(tidyr)
library(FactoMineR)
library(Matching)
library(gmodels)
library(class)

setwd("/Users/isysjo/Documents/Summer REU 2018/SportsAnalytics/R")
source("../Isys/cluster_id_model.R")

# get lineups
all_lineups <- read.csv('../Data/2017_2018/train_for_lineups_full.csv')

#cluster lineups
numeric_lin <- all_lineups %>% dplyr::select(TOTAL_MIN:TOV, -TOTAL_MIN, -LINEUP, -TOT_PT_DIFF)
numeric_lin_scaled <- scale(numeric_lin)
#numeric_lin_points <- all_lineups %>% dplyr::select(TOTAL_MIN:TOV, -TOTAL_MIN, -LINEUP)
agg_line <- agnes(numeric_lin_scaled, method="ward")
#diana_line <- diana(numeric_lin_scaled)
#plot(agg_line)
#plot(diana_line)

clusters_agg_line <- cbind(all_lineups, cluster = cutree(agg_line,5))
#clusters_diana_line <- cbind(all_lineups, cluster = cutree(diana_line,5))

pcat <- PCA(numeric_lin_scaled)
#plot(pcat, choix = "ind",col.ind=rainbow(5)[clusters_agg_line$cluster], label = "none")

# get cluster assignments post PCA
agnes_pca <- agnes(pcat$ind$coord %>% scale, method="ward")
clusters_pca_agg <- cbind(all_lineups, cluster = cutree(agnes_pca,5))

# get clusters for individual players
# new data
clean_individual_player_data <- function(player_table) {
  player_table <- player_table %>%
    filter(MIN > 0)
  return(player_table)
}

ap_training <- read.csv('../Data/train_test/player_train_filtered_for_lineups.csv')
aggregate_training <- ap_training %>% clean_individual_player_data() %>% filter(MIN > 50)

filtered_training <- aggregate_training %>% dplyr::select(FGM:BOX_OUTS, -POS)
filtered_training[is.na(filtered_training)] <- 0
filtered_scaled <- scale(filtered_training)

agg_t <- agnes(filtered_scaled, method= "ward")

#dian_t <- diana(filtered_scaled)
clusters_agg <- cbind(aggregate_training, cluster = cutree(agg_t,5))
#clusters_diana <- cbind(aggregate_training, cluster = cutree(dian_t,4))


# get lineup types for all lineups
all_lineup_types <- sapply(all_lineups$LINEUP %>% as.character, function(x) get_lineup_type(x, clusters_agg))
#bind the lineup types with the clusters_added
agnes_lineup_types <- cbind(clusters_agg_line, LINEUP_ID = all_lineup_types)
rownames(agnes_lineup_types) <- NULL
pca_agg_LT <- cbind(clusters_pca_agg, LINEUP_ID = all_lineup_types)
# Pairwise Scatter Plots s
clPairs(numeric_lin_scaled, cl = clusters_agg_line$cluster)

#make table of proportions
ct <- gmodels::CrossTable(agnes_lineup_types$LINEUP_ID, agnes_lineup_types$cluster,
                 prop.r = TRUE, prop.c = TRUE, prop.t=TRUE, prop.chisq = FALSE)


# z-score analysis: tells average v score for each variable for a given cluster or vertex
zscores_for_cluster <- function(players_in_cluster, data) {

  zscores <- c()
  for(i in 1:length(data[1,])) {
  if(length(players_in_cluster) == length(data[1,])) {
      zscores[i] <- mean(players_in_cluster[i])
  }
  else zscores[i] <- mean(players_in_cluster[,i])
}
  return(zscores)
}


# use z-score matrix to find features of each cluster
## make table of attributes and the ks-test p-values for each cluster
cluster_1 <- numeric_lin_points[which(clusters_agg_line$cluster == 1),] %>% scale
cluster_2 <- numeric_lin_points[which(clusters_agg_line$cluster == 2),] %>% scale
cluster_3 <- numeric_lin_points[which(clusters_agg_line$cluster == 3),] %>% scale
cluster_4 <- numeric_lin_points[which(clusters_agg_line$cluster == 4),] %>% scale
cluster_5 <- numeric_lin_points[which(clusters_agg_line$cluster == 5),] %>% scale

zlist <- list()
zlist[[1]] <- zscores_for_cluster(cluster_1,numeric_lin_scaled)
zlist[[2]] <- zscores_for_cluster(cluster_2,numeric_lin_scaled)
zlist[[3]] <- zscores_for_cluster(cluster_3,numeric_lin_scaled)
zlist[[4]] <- zscores_for_cluster(cluster_4,numeric_lin_scaled)
zlist[[5]] <- zscores_for_cluster(cluster_5,numeric_lin_scaled)

zscores <- do.call(rbind, zlist)
colnames(zscores) <- colnames(numeric_lin_scaled)
rownames(zscores) <- c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5")

## EDA
# check to see if the lineup types in a given cluster have different values for point differential
ggplot(agnes_lineup_types[which(clusters_agg_line$cluster == 1),], aes(LINEUP_ID, TOT_PT_DIFF)) + geom_bar(stat="identity") + labs(title="Cluster 1 Lineup Types vs PT Diff")
ggplot(agnes_lineup_types[which(clusters_agg_line$cluster == 2),], aes(LINEUP_ID, TOT_PT_DIFF)) + geom_bar(stat="identity") + labs(title="Cluster 2 Lineup Types vs PT Diff")
ggplot(agnes_lineup_types[which(clusters_agg_line$cluster == 3),], aes(LINEUP_ID, TOT_PT_DIFF)) + geom_bar(stat="identity") + labs(title="Cluster 3 Lineup Types vs PT Diff")
ggplot(agnes_lineup_types[which(clusters_agg_line$cluster == 4),], aes(LINEUP_ID, TOT_PT_DIFF)) + geom_bar(stat="identity") + labs(title="Cluster 4 Lineup Types vs PT Diff")
ggplot(agnes_lineup_types[which(clusters_agg_line$cluster == 5),], aes(LINEUP_ID, TOT_PT_DIFF)) + geom_bar(stat="identity") + labs(title="Cluster 5 Lineup Types vs PT Diff")

# lineup type bar graphs
ggplot(agnes_lineup_types[which(agnes_lineup_types$LINEUP_ID %>% as.character == "12345"),], aes(cluster, TOT_PT_DIFF, colour=cluster)) + geom_bar(stat="identity") + labs(title="Pt Diff of Lineup ID 12345 by Cluster")
ggplot(agnes_lineup_types, aes(LINEUP_ID, TOT_PT_DIFF, colour=rainbow(5)[cluster])) + geom_bar(stat="identity")
ggplot(agnes_lineup_types, aes(LINEUP_ID, REB, colour=rainbow(5)[cluster])) + geom_bar(stat="identity")
ggplot(agnes_lineup_types, aes(LINEUP_ID, STL, colour=rainbow(5)[cluster])) + geom_bar(stat="identity")
ggplot(agnes_lineup_types, aes(LINEUP_ID, AST, colour=rainbow(5)[cluster])) + geom_bar(stat="identity")
ggplot(agnes_lineup_types, aes(LINEUP_ID, TOV, colour=rainbow(5)[cluster])) + geom_bar(stat="identity")


### testing
# given a new lineup of players, see the probabilities that they are in each cluster?
# and then for each case, find the predicted plus-minus for whatever clusters it's likely in
# compare
# refine by comparing stats for indiduals verses their lineup

# bring in testing data
testing_data <- read.csv("test_for_lineups_full.csv")
numeric_test <- testing_data %>% dplyr::select(TOTAL_MIN:TOV, -TOTAL_MIN, -LINEUP)
numeric_test_scaled <- scale(numeric_test)

# get the lineup types of testing data
all_testing_types <- sapply(testing_data$LINEUP %>% as.character, function(x) get_lineup_type(x, clusters_agg))
#bind the lineup types with the clusters_added
agnes_testing_types <- cbind(testing_data, LINEUP_ID = all_testing_types)
rownames(agnes_testing_types) <- NULL

#get prediction matrix for cluster+lineup_id model
predictions <- sapply(agnes_testing_types$LINEUP_ID, function(x) predict_ps(x, agnes_lineup_types))

# find the best possibly performance of model on testing data
opt_error <- get_optimal_error(predictions)

predicted_stats <- get_predicted_stats()
#get predictions and errors from model
agnes_model_results <- get_errors_and_predictions(predictions, predicted_stats,agnes_lineup_types)

plot(agnes_model_results$predictions[,3],testing_data$TOT_PT_DIFF)



# find error with just regression
error_reg <- mean((testing_data$TOT_PT_DIFF-predicted_points)^2)

# regression error 0.151
#results for cluster numbers of 4,5,6
# 4, optimal - 0.04854397
#KNN: 0.2278257
#MULTIN: 0.1839281
#LDA: 0.1795391

# 5, optimal: 0.04400373
#KNN 0.2190089
#MULTIN 0.1783663
#LDA 0.1770311

#6, optimal 0.041
#KNN 0.213
#MULTIN 0.179111
#LDN 0.1770311

# check diagnostics and assumptions for LDA and MULTINOM

# when using clustering results from PCA, the findings are as follows
#4, optimal 0.05687454
# KNN:
# MULTIN: 0.1906256
# LDA: 0.1959379

#5, optimal: 0.05358635
# KNN:
# MULTIN:0.1857822
# LDA: 0.1904589

#6, optimal:
# KNN:
# MULTIN:
# LDA:

#using median:
# optimal .0.0385483
# KNN: .251
#MULTIN 0.2166187
#LDA 0.2223239