---
title: "PCA_analysis"
author: "Isys"
date: "6/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## R Markdown
library(mclust)
library(cluster)
library(FactoMineR)
library(descr)
library(dplyr)
library(tidyr)

setwd("/Users/isysjo/Documents/Summer REU 2018/SportsAnalytics/R")

# source('preprocess_individuals.R')

# new data
clean_individual_player_data <- function(player_table) {
  player_table <- player_table %>%
    filter(MIN > 0)
  return(player_table)
}

# modifications to load all players
path_to_files <- '../Data/2017_2018/'
filelist = paste0(path_to_files, list.files(path_to_files, 'all_per_minute_2017_2018.csv'))
all_players <- read.csv(filelist)

# get aggregate player data
 aggregate_players <- all_players %>% clean_individual_player_data()

# remove players who haven't played more than 50 minutes
aggregate_players <- aggregate_players %>% filter(MIN > 50)

# get numeric data (excluding result, GS, MP, and GmSc)
numeric <- aggregate_players %>% select(FGM:BOX_OUTS, -POS)

# set NA percentages to 0
numeric[is.na(numeric)] <- 0

# scale numeric data before clustering
numeric_scaled <- scale(numeric)

#divisive clustering method
dian <- diana(numeric_scaled)

clusters_added_diana <- cbind(aggregate_players, cluster = cutree(dian,3))

# do pca
pca <- PCA(numeric_scaled)
pca_coord <- pca$ind$coord
pca_coord[is.na(pca_coord)] <- 0
pca_coord_scaled <- scaled(pca_coord)


# overlay scaled points colored coded by cluster on the variable factor plot
points(numeric_scaled, col=ifelse(clusters_added_diana$cluster ==1, "red", ifelse(clusters_added_diana$cluster ==2, "blue", "green")), xlim= c(-.2,1))


# summary(pca) gives eigenvalues for the PCA dimensions and the % percentage each accounts for
# one of the rules of thumbs for choosing a number of dimensions is to use the ones who's eigenvalues
# are > 1 OR stop adding compoments when variance % exceeds some high value



## doing PCA and the clustering and color coding based on components
pca <- PCA(numeric_scaled)
pca_coord <- pca$ind$coord
pca_coord[is.na(pca_coord)] <- 0
pca_coord_scaled <- scale(pca_coord)

model_clust_pca2 <- Mclust(pca_coord_scaled, G=1:9, modelNames = mclust.options("emModelNames"))
combi_pca <- clustCombi(model_clust_pca2)
clusters_pca <- unlist(combi_pca$classification[3])
clusters_added_PCA <- cbind(pca_coord_scaled, cluster = clusters_pca) %>% matrix(288,6) %>% as.data.frame()

plot(pca_coord_scaled, col = ifelse(clusters_added_PCA$V6 ==1, "red", ifelse(clusters_added_PCA$V6 ==2, "blue", "green")))


# Pairwise Scatter Plots s
clPairs(scaled_chosen, cl = clusters_added_diana$Pos)
# table of correlations
cor(scaled_chosen)