---
title: "TDA Analysis"
author: "Isys"
date: "June 12, 2018"
output: html_document
---

## R Markdown

library(gmodels)
library(descr)
library(dplyr)
library(tidyr)
library(mclust)
library(FactoMineR)
library(TDAmapper)
library(igraph)

setwd("/Users/isysjo/Documents/Summer REU 2018/SportsAnalytics/R")

source('preprocess_individuals.R')

# new data
clean_individual_player_data <- function(player_table) {
  player_table <- player_table %>%
    filter(MIN > 0)
  return(player_table)
}

# modifications to load all players
path_to_files <- '../Data/2017_2018/'
filelist = paste0(path_to_files, list.files(path_to_files, 'all_per_minute_2017_2018.csv'))
all_players <- read.csv(filelist)
# get the training set and do same things to training set as full set
ap_training <- read.csv('../Data/train_test/player_train.csv')

clean_load <- all_players %>% clean_individual_player_data()

# get aggregate player data
 aggregate_players <- clean_load
aggregate_training <- ap_training %>% clean_individual_player_data()

# remove players who haven't played more than 50 minutes
aggregate_players <- aggregate_players %>% filter(MIN > 50)
aggregate_training <- aggregate_training %>% filter(MIN > 50)

# get numeric data (excluding result, GS, MP, and GmSc)
numeric <- aggregate_players %>% select(FGM:BOX_OUTS, -POS)
numeric_training <- aggregate_training %>% select(FGM:BOX_OUTS, -POS)

# set NA percentages to 0
numeric[is.na(numeric)] <- 0
numeric_training[is.na(numeric_training)] <- 0

## scale numeric data before clustering
numeric_scaled <- scale(numeric)
ns_training <- scale(numeric_training)



# z-score analysis: tells average v score for each variable for a given cluster or vertex
zscores_for_cluster <- function(players_in_cluster, data) {
  players <- unlist(players_in_cluster)
  values <- data[players,]
  zscores <- c()
  for(i in 1:length(data[1,])) {
  if(length(players) == 1) {
      zscores[i] <- mean(values[i])
  }
  else zscores[i] <- mean(values[,i])
}
  return(zscores)
}

## tda on training set
filtered_training <- aggregate_training %>% select(FGM:BOX_OUTS, -POS, -PTS, -PLUS_MINUS)
filtered_training[is.na(filtered_training)] <- 0
filtered_scaled <- scale(filtered_training)

set.seed("1")
m1.training <- mapper1D(
  distance_matrix = dist(filtered_scaled),
  filter_values = ns_training[,19],
  num_intervals = 10,
  percent_overlap = 50,
  num_bins_when_clustering = 10)
g1.training <- graph.adjacency(m1.training$adjacency, mode="undirected")
plot(g1.training, layout = layout.auto(g1.training) )

set.seed("123")
nba.mapper.training <- mapper(
  dist_object = dist(filtered_scaled),
  filter_values = list(ns_training[,19],ns_training[,20]),
  num_intervals = c(4,4),
  percent_overlap = 50,
  num_bins_when_clustering = 10)
nba.graph.training <- graph.adjacency(nba.mapper.training$adjacency, mode="undirected")
plot(nba.graph.training,
     layout = layout.auto(nba.graph.training),
     main ="TDA" )




interesting_group_1 <- filtered_training[unique(
      sort(unlist(nba.mapper.training$points_in_vertex[c(1,4,5)]))),]
interesting_group_2 <- filtered_training[unique(
      sort(unlist(nba.mapper.training$points_in_vertex[c(9,10,11,16,12)]))),]
interesting_group_3 <- filtered_training[unique(
      sort(unlist(nba.mapper.training$points_in_vertex[c(20,18,25)]))),]
interesting_group_4 <- filtered_training[unique(
      sort(unlist(nba.mapper.training$points_in_vertex[c(21,26,27)]))),]
interesting_group_5 <- filtered_training[unique(
      sort(unlist(nba.mapper.training$points_in_vertex[c(6,7,3,14)]))),]

group_comparison <- function(group_1) {
    pvals <- c()
    for(i in 1:length(filtered_training[1,])) {
        test <- ks.boot(group_1[,i], filtered_training[,i], alternative = "two.sided")
        pvals[i] <- test$p.value
    }
    return(pvals)
}

g1 <- group_comparison(interesting_group_1)
g2 <- group_comparison(interesting_group_2)
g3 <- group_comparison(interesting_group_3)
g4 <- group_comparison(interesting_group_4)
g5 <- group_comparison(interesting_group_5)


# plot mapper graph with vertex size proportional to the number of points inside
m1.graph.training <- graph.adjacency(m1.training$adjacency, mode="undirected")

y.mean.vertex <- rep(0,m1.training$num_vertices)
for (i in 1:m1.training$num_vertices){
  points.in.vertex <- m1.training$points_in_vertex[[i]]
  y.mean.vertex[i] <-mean((ns_training[,20][points.in.vertex]))
}

vertex.size <- rep(0,m1.training$num_vertices)
for (i in 1:m1.training$num_vertices){
  points.in.vertex <- m1.training$points_in_vertex[[i]]
  vertex.size[i] <- length((m1.training$points_in_vertex[[i]]))
}

plot(m1.graph.training, layout = layout.auto(m1.graph.training) )

y.mean.vertex.grey <- grey(1-(y.mean.vertex - min(y.mean.vertex))/(max(y.mean.vertex) - min(y.mean.vertex) ))
V(m1.graph.training)$color <- y.mean.vertex.grey
V(m1.graph.training)$size <- vertex.size
plot(m1.graph.training,main ="Mapper Graph")
legend(x=-2, y=-1, c("y small","y medium","large y"),pch=21,
       col="#777777", pt.bg=grey(c(1,0.5,0)), pt.cex=2, cex=.8, bty="n", ncol=1)

# pca analysis on training set
pca_training <- PCA(ns_training)
pcat_coord <- pca_training$ind$coord
pcat_coord[is.na(pcat_coord)] <- 0
pcat_coord_scaled <- scale(pcat_coord)

set.seed("1")
m2.t <- mapper1D(
  distance_matrix = dist(pcat_coord_scaled),
  filter_values = pcat_coord_scaled[,1],
  num_intervals = 10,
  percent_overlap = 50,
  num_bins_when_clustering = 10)
g2.t <- graph.adjacency(m2.t$adjacency, mode="undirected")
plot(g2.t, layout = layout.auto(g2.t) )

## tda analysis on full data set
chosen <- aggregate_players %>% select(FGM:BOX_OUTS, -POS, -PTS, -PLUS_MINUS)
chosen[is.na(chosen)] <- 0
chosen_scaled <- scale(chosen) 

set.seed("1")
m1 <- mapper1D(
  distance_matrix = dist(chosen_scaled),
  filter_values = numeric_scaled[,19],
  num_intervals = 10,
  percent_overlap = 50,
  num_bins_when_clustering = 10)
g1 <- graph.adjacency(m1$adjacency, mode="undirected")
plot(g1, layout = layout.auto(g1) )

set.seed("123")
nba.mapper <- mapper(
  dist_object = dist(chosen_scaled),
  filter_values = list(numeric_scaled[,19],numeric_scaled[,20]),
  num_intervals = c(4,4),
  percent_overlap = 40,
  num_bins_when_clustering = 10)
nba.graph <- graph.adjacency(nba.mapper$adjacency, mode="undirected")
plot(nba.graph,
     layout = layout.auto(nba.graph),
     main ="TDA" )
                  
# plot mapper graph with vertex size proportional to the number of points inside
m1.graph <- graph.adjacency(m1$adjacency, mode="undirected")

y.mean.vertex <- rep(0,m1$num_vertices)
for (i in 1:m1$num_vertices){
  points.in.vertex <- m1$points_in_vertex[[i]]
  y.mean.vertex[i] <-mean((numeric_scaled[,20][points.in.vertex]))
}

vertex.size <- rep(0,m1$num_vertices)
for (i in 1:m1$num_vertices){
  points.in.vertex <- m1$points_in_vertex[[i]]
  vertex.size[i] <- length((m1$points_in_vertex[[i]]))
}

plot(m1.graph, layout = layout.auto(m1.graph) )

y.mean.vertex.grey <- grey(1-(y.mean.vertex - min(y.mean.vertex))/(max(y.mean.vertex) - min(y.mean.vertex) ))
V(m1.graph)$color <- y.mean.vertex.grey
V(m1.graph)$size <- vertex.size
plot(m1.graph,main ="Mapper Graph")
legend(x=-2, y=-1, c("y small","y medium","large y"),pch=21,
       col="#777777", pt.bg=grey(c(1,0.5,0)), pt.cex=2, cex=.8, bty="n", ncol=1)
       
# z score table 
allzscores <- NULL
for(j in 1:length(m1$points_in_vertex)) {
allzscores <- rbind(allzscores, j=zscores_for_cluster(m1$points_in_vertex[j], numeric_scaled))
rownames(allzscores)[j] <- paste("Vertex",j)

}
colnames(allzscores) <- colnames(numeric_scaled)

allzscores <- allzscores[c(1:15),]

## pca with full data set
pca <- PCA(numeric_scaled)
pca_coord <- pca$ind$coord
pca_coord[is.na(pca_coord)] <- 0
pca_coord_scaled <- scale(pca_coord)

set.seed("1")
m2 <- mapper1D(
  distance_matrix = dist(pca_coord_scaled),
  filter_values = pca_coord_scaled[,1],
  num_intervals = 10,
  percent_overlap = 50,
  num_bins_when_clustering = 10)
g2 <- graph.adjacency(m1$adjacency, mode="undirected")
plot(g2, layout = layout.auto(g2) )

allzscores_pca <- NULL
for(j in 1:length(m2$points_in_vertex)) {
allzscores_pca <- rbind(allzscores_pca, j=zscores_for_cluster(m2$points_in_vertex[j], pca_coord_scaled))
rownames(allzscores_pca)[j] <- paste("Vertex",j)

}

colnames(allzscores_pca) <- colnames(pca_coord_scaled)